# permissions for end users to edit kubebuilders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubebuilder-editor-role
rules:
- apiGroups:
  - demo.apps.acme.com
  resources:
  - kubebuilders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - demo.apps.acme.com
  resources:
  - kubebuilders/status
  verbs:
  - get
