# permissions for end users to view kubebuilders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubebuilder-viewer-role
rules:
- apiGroups:
  - demo.apps.acme.com
  resources:
  - kubebuilders
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - demo.apps.acme.com
  resources:
  - kubebuilders/status
  verbs:
  - get
