# permissions for end users to view webstores.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: webstore-viewer-role
rules:
- apiGroups:
  - apps.acme.com
  resources:
  - webstores
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.acme.com
  resources:
  - webstores/status
  verbs:
  - get
