# permissions for end users to edit webstores.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: webstore-editor-role
rules:
- apiGroups:
  - apps.acme.com
  resources:
  - webstores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.acme.com
  resources:
  - webstores/status
  verbs:
  - get
