# permissions for end users to edit operatorsdks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operatorsdk-editor-role
rules:
- apiGroups:
  - demo.apps.acme.com
  resources:
  - operatorsdks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - demo.apps.acme.com
  resources:
  - operatorsdks/status
  verbs:
  - get
